version: '2'

services:

  hub:
    build:
      context: .
      dockerfile: Dockerfile-hub
    ports:
      - "4444:4444"

  node:
    depends_on:
      - hub
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "5555:5555"
    links:
      - hub:selenium-hub
