FROM ubuntu
MAINTAINER SamFrier

ADD https://goo.gl/Lyo36k /opt/selenium-server-standalone.jar
RUN apt-get update
RUN apt-get install -y openjdk-8-jre openjdk-8-jdk

#RUN apt-get install -y firefox
#ADD https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz /opt/geckodriver.tar.gz

EXPOSE 4444

ENTRYPOINT java -jar /opt/selenium-server-standalone.jar -role hub
