version: '2'

services:

  hub:
    build:
      context: .
      dockerfile: Dockerfile-hub
    ports:
      - "4444:4444"

  node-firefox:
    depends_on:
      - hub
    build:
      context: .
      dockerfile: Dockerfile-node-firefox
    links:
      - hub:selenium-hub

#  node-chrome:
#    depends-on:
#      - hub
#    build:
#      context: .
#      dockerfile: Dockerfile-node-chrome
#    links:
#      - hub:selenium-hub
