FROM ubuntu
MAINTAINER SamFrier

ADD https://goo.gl/Lyo36k /opt/selenium-server-standalone.jar
RUN apt-get update
RUN apt-get install -y openjdk-8-jre openjdk-8-jdk

EXPOSE 4444

ENTRYPOINT java -jar /opt/selenium-server-standalone.jar -role hub
