FROM ubuntu
MAINTAINER SamFrier

# Download Selenium Server
ADD https://goo.gl/Lyo36k /opt/selenium-server-standalone.jar

# Install Java
RUN apt-get update
RUN apt-get install -y openjdk-8-jre openjdk-8-jdk

# Install Chrome + driver
RUN apt-get install -y wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable
ADD https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip /opt/chrome/chromedriver_linux64.zip
RUN apt-get install -y unzip
WORKDIR /opt/chrome
RUN unzip chromedriver_linux64.zip
ENV PATH $PATH:/opt/chrome
# haha, good luck

# Set Chrome to run in headless mode(?)
RUN apt-get install -y xvfb
ENV DISPLAY :1

ENTRYPOINT Xvfb :1 &\
java -jar /opt/selenium-server-standalone.jar -role node -hub http://selenium-hub:4444/grid/register -browser browserName=chrome,maxInstances=5
