FROM ubuntu
MAINTAINER SamFrier

# Download Selenium Server
ADD https://goo.gl/Lyo36k /opt/selenium-server-standalone.jar

# Install Java
RUN apt-get update
RUN apt-get install -y openjdk-8-jre openjdk-8-jdk

# Install Firefox + related drivers
RUN apt-get install -y firefox
ADD https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz /opt/gecko/geckodriver-v0.11.1-linux64.tar.gz
WORKDIR /opt/gecko
RUN tar zxvf /opt/gecko/geckodriver-v0.11.1-linux64.tar.gz
ENV PATH $PATH:/opt/gecko

# Set Firefox to run in headless mode
RUN apt-get install -y xvfb 
ENV DISPLAY :1

ENTRYPOINT Xvfb :1 &\
java -jar /opt/selenium-server-standalone.jar -role node -hub http://selenium-hub:4444/grid/register -browser browserName=firefox,maxInstances=5
